# Generated by Django 4.2.17 on 2024-12-11 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('code', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=16, null=True)),
                ('myid', models.CharField(max_length=32)),
                ('firstname', models.CharField(max_length=45)),
                ('lastname', models.CharField(max_length=45)),
                ('nickname', models.CharField(max_length=45, null=True)),
                ('hiredate', models.DateField(blank=True, null=True)),
                ('email', models.CharField(max_length=65, null=True)),
                ('officephone', models.CharField(max_length=16, null=True)),
                ('birthdate', models.CharField(max_length=10, null=True)),
                ('lunch', models.TimeField(null=True)),
                ('initials', models.CharField(max_length=3, null=True)),
                ('payroll', models.CharField(max_length=16, null=True)),
                ('type', models.CharField(max_length=16, null=True)),
                ('routingslip', models.BooleanField()),
                ('receptionrole', models.CharField(max_length=8, null=True)),
                ('alphabet', models.CharField(max_length=26, null=True)),
                ('createdate', models.DateField(blank=True, null=True)),
                ('employee_modifydate', models.DateField(blank=True, null=True)),
                ('modifiedby', models.DateField(blank=True, null=True)),
                ('terminal', models.BooleanField()),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='employee_department', to='info.department')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='employee_group', to='info.group')),
                ('position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='employee_position', to='info.position')),
                ('supervisor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='employee_supervisor', to='info.employee')),
            ],
            options={
                'ordering': ['lastname', 'firstname'],
            },
        ),
    ]
