# Generated by Django 4.2.17 on 2024-12-11 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='employee_modifydate',
            new_name='modifydate',
        ),
        migrations.AlterField(
            model_name='employee',
            name='modifiedby',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='employee_modifiedby', to='info.employee'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='routingslip',
            field=models.BooleanField(null=True),
        ),
    ]
