# Generated by Django 4.2.17 on 2024-12-11 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_rename_employee_modifydate_employee_modifydate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='createdate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='modifydate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
