# Generated by Django 4.2.17 on 2024-12-11 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_alter_employee_createdate_alter_employee_modifydate'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='livestatus',
            field=models.BooleanField(default=1),
        ),
    ]
