# Generated by Django 4.2.17 on 2024-12-12 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0007_employee_programmer'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppRequests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('requestdate', models.DateField()),
                ('subject', models.CharField(max_length=256)),
                ('status', models.IntegerField(blank=True, choices=[(1, 'C'), (2, 'P'), (3, 'V'), (4, 'W')], default=2)),
                ('priority', models.IntegerField(blank=True, choices=[(1, 'H'), (2, 'L'), (3, 'M')], default=2)),
                ('source', models.IntegerField(blank=True, choices=[(1, 'Banner'), (2, 'BOR'), (3, 'CL'), (4, 'F&S'), (5, 'FED'), (6, 'OSFA'), (7, 'OTH'), (8, 'ST'), (9, 'UGA')], default=7)),
                ('deadline', models.CharField(max_length=32, null=True)),
                ('comment', models.TextField(null=True)),
                ('complete_date', models.DateField(null=True)),
                ('delete_date', models.DateField(null=True)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='requests_department', to='info.department')),
            ],
        ),
    ]
