# Generated by Django 4.2.17 on 2024-12-17 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0008_apprequests'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='position',
            options={'ordering': ['name']},
        ),
    ]
