# Generated by Django 4.2.17 on 2024-12-17 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0009_alter_department_options_alter_group_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('displaytext', models.CharField(max_length=256)),
                ('url', models.CharField(max_length=256)),
                ('linktype', models.IntegerField(blank=True, choices=[(0, 'Quick Link'), (1, 'Approved Software')], default=1)),
            ],
        ),
    ]
