# Generated by Django 4.2.17 on 2024-12-17 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0010_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
